### ISSUE TITLE
Output scrambled up with --shuffle flag

### ISSUE THREAD

**Issue by Sup3Legacy** [Lioness100/guess-that-lang#14]
Hi!

There seems to be some issues with the UI when line shuffling is enabled.

![image](https://user-images.githubusercontent.com/52403031/184879819-da114539-ada0-4a18-8f83-5c16f96da49b.png)

Version:

![image](https://user-images.githubusercontent.com/52403031/184879991-edbe7d3a-f374-4b64-8b48-b1d7e407ac21.png)

I may look into that and submit a PR if I have some time.

**Comment by Lioness100** [comment]
Thanks for opening an issue!! I'll try to reproduce and then publish a fixed version soon :)

**Comment by Sup3Legacy** [comment]
Without looking at the code, I'd say that the lines are getting displayed in top-bottom order even when shuffled, thus resulting in this behaviour.

**Comment by Lioness100** [comment]
Fixed! I think this problem was created in https://github.com/Lioness100/guess-that-lang/commit/f19d3014a376b18134e88500044c330942d7c385

**Comment by Sup3Legacy** [comment]
Seems to be working, thanks!
