### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by Sup3Legacy** [Lioness100/guess-that-lang#16]
Hi!

Just packaged `guess-that-lang` in the [AUR](https://aur.archlinux.org/packages/guess-that-lang-bin).

**Comment by Lioness100** [comment]
Thank you! I don't know anything about listing stuff on package providers like that, but won't that need to be updated every version?

**Comment by Sup3Legacy** [comment]
Well yeah it is supposed to remain up-to-date with the upstream source with some margin!

**Comment by Lioness100** [comment]
That might be hard, because I publish versions fairly frequently and don't want you to have to update it on AUR everytime

**Comment by Lioness100** [comment]
Closing this because there's nothing that needs to be fixed
