### ISSUE TITLE
Will not compile on Linux

### ISSUE THREAD

**Issue by BartMassey** [Lioness100/guess-that-lang#7]
Turns out `ansi_term::enable_ansi_support()` is available only on Windows. Change the imports in `terminal.rs` to

```rust
use ansi_term::{
    ANSIGenericStrings,
    Color::{self, Fixed, RGB},
};
#[cfg(windows)]
use ansi_term::enable_ansi_support;
```

**Comment by Lioness100** [comment]
Nice catch! Fixed in https://github.com/Lioness100/guess-that-lang/commit/2034218d34e318cf461deff3eab73068c1be9fa1
