### ISSUE TITLE
Language example consists of just a block of comment(s)

### ISSUE THREAD

**Issue by FlareFlo** [Lioness100/guess-that-lang#9]
![image](https://user-images.githubusercontent.com/78537307/184435414-316458da-968f-43f5-ab72-b7d2ca32e8c2.png)
![image](https://user-images.githubusercontent.com/78537307/184436056-98502cb2-895f-48a3-911a-90901618161d.png)
I generally would suggest removing all kinds of comments from the shown example pieces, as they typically confuse more than they help.

**Comment by FlareFlo** [comment]
I would simply take a set of syntax rules defined for every language, and filter out these blocks from any code example.

**Comment by Lioness100** [comment]
Another method I can think of, since there's only 1-2 themes we're using, is checking if the start of a line is highlighted with the specific color that comments are highlighted with, and if so, removing them. This would be more maintainable and easier because we wouldn't have to create overrides for every language, although could end up being less maintainable if sometime in the future we introduce a feature to let people customize themes. That crate is something to take note of though, thanks for sharing it :)

**Comment by FlareFlo** [comment]
> Another method I can think of, since there's only 1-2 themes we're using, is checking if the start of a line is highlighted with the specific color that comments are highlighted with, and if so, removing them. This would be more maintainable and easier because we wouldn't have to create overrides for every language, although could end up being less maintainable if sometime in the future we introduce a feature to let people customize themes. That crate is something to take note of though, thanks for sharing it :)

I would put the color-based comment highlighter behind a (maybe default) feature, as it is a rather good idea for the time being.

**Comment by Lioness100** [comment]
By "feature", do you mean a cargo feature? If you think it should be optional, wouldn't it be better to use a CLI flag since you can change it per-game?

**Comment by FlareFlo** [comment]
> By "feature", do you mean a cargo feature? If you think it should be optional, wouldn't it be better to use a CLI flag since you can change it per-game?

Sorry yes, should've said flag not feature

**Comment by Lioness100** [comment]
Using `line.starts_with("\u{1b}[38;2;117;113;94m")` I can consistently detect whether the line is a comment for all languages. Refactoring the state to pass around highlighted lines might take some work though.

**Comment by FlareFlo** [comment]
How about filtering the comment lines before returning the string content.
https://github.com/Lioness100/guess-that-lang/blob/4efb6ce2be468c2d8af28943fc273d5866d879fd/src/github.rs#L156-L165

**Comment by Lioness100** [comment]
I think it should be filtered out in `trim_text`, because that function also limits the code to 10 non-empty lines, and it would be needlessly expensive to highlight and filter 100 lines of code when you get the gist if you're only taking 10 of them anyways.

**Comment by Lioness100** [comment]
I decided not to add a CLI flag and just make it mandatory.
